on:
  pull_request:
    branches: [main]
  workflow_dispatch:

name: Build and Push Docker Image TO Amazon ECR

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ECR_REPOSITORY_NAME: myops/ecs-micro-svc-demo
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@main

      - name: Build, tag, and push image to Amazon ECR
        id: build-deploy-image
        uses: whoan/docker-build-with-cache-action@master
        with:
          username: "${{ env.AWS_ACCESS_KEY_ID }}"
          password: "${{ env.AWS_SECRET_ACCESS_KEY }}"
          registry: ${{ steps.login-ecr.outputs.registry }}
          image_name: ${{ env.AWS_ECR_REPOSITORY_NAME }}
          image_tag: ${{ env.IMAGE_TAG }}
          push_image_and_stages: true
